name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # == CHECK == #
  check:
    name: Check nightly beta stable and MSRV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain:
          - 1.56.0
          - stable
          # Try to guard against a near-future regression.
          - beta
        cargo-locked: ["--locked", ""]
        exclude:
          # MSRV guarantee only stands for `.lock`-tested dependencies.
          - rust-toolchain: 1.56.0
            cargo-locked: ''
    steps:
      - name: Install Rust toolchain
        run: |
          rustup toolchain install "${{ matrix.rust-toolchain }}" --profile=minimal
          rustup override set "${{ matrix.rust-toolchain }}"

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.cargo-locked != '--locked'
        run: cargo update -v

      - name: Cargo check
        env:
          RUSTC_BOOTSTRAP: 1
        run: cargo check ${{ matrix.cargo-locked }}

  # == BUILD & TEST == #
  build-and-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    needs: [check]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchain:
          - 1.56.0
          - stable
    steps:
      - name: Install Rust toolchain
        run: |
          rustup toolchain install "${{ matrix.rust-toolchain }}"
          rustup override set "${{ matrix.rust-toolchain }}"

      - name: Clone repo
        uses: actions/checkout@v2

      - run: cargo test

  required-jobs:
    name: 'All the required jobs'
    needs:
      - check
      - build-and-test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: 'Check success of the required jobs'
        run: |
          RESULT=$(echo "${{ join(needs.*.result, '') }}" | sed -e "s/success//g")
          if [ -n "$RESULT" ]; then
            echo "❌"
            false
          fi
          echo "✅"
