name: Cron CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,5'

jobs:
  # == TEST == #
  test-no-ui:
    name: (Check & Build &) Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchains:
        rust-toolchain:
          # Future-proof against compiler-regressions
          - beta
          - nightly
        cargo-locked: ["--locked", ""]
        include:
          # Also future-proof against semver breakage from dependencies.
          # (But we don't have any dependencies yet, so don't actually run this.)
          # - os: ubuntu-latest
          #   rust-toolchain: stable
          #   cargo-locked: ''
    steps:
      - name: Install Rust toolchain
        run: |
          rustup toolchain install "${{ matrix.rust-toolchain }}"
          rustup override set "${{ matrix.rust-toolchain }}"

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.cargo-locked != '--locked'
        run: cargo update -v

      - name: Cargo test
        env:
          RUSTC_BOOTSTRAP: 1
        run: cargo test ${{ matrix.cargo-locked }} --features nightly
